apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ffc-demo-web
  namespace: config-cluster-flux
spec:
  values:
    name: ffc-demo-web
    namespace: ffc-demo
    image: sndadpinfcr1401.azurecr.io/image/ffc-demo-web:4.32.2 # {"$imagepolicy": "config-cluster-flux:ffc-demo-web"}
    labels:
      component: web
    containerConfigMap:
      configServiceUrl: 'https://sndadpinfac1401.azconfig.io'
    ingress:
      class: nginx
      endpoint: ffc-demo-web
      server: snd1.adp.defra.gov.uk
    deployment:
      priorityClassName: default
