apiVersion: batch/v1
kind: Job
metadata:
  name: ffc-demo-claim-service-db-migration
  namespace: config-cluster-flux
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ffc-demo-claim-service-db-migration
        image: sndcdoinfcr2401p.azurecr.io/ffc-demo-claim-service-migration:dev-wo-cmd
        command:
          - sh
          - -c
          # - echo $(find $(pwd))
          - "/liquibase/scripts/migration/database-up"
        env:
        - name: POSTGRES_HOST
          value: "sndadpdbsps1401.postgres.database.azure.com"
        - name: SCHEMA_NAME
          value: "public"
        - name: POSTGRES_DB
          value: "ffc_demo_claim"
        - name: POSTGRES_PORT
          value: "5432"
        envFrom:
        - secretRef:
            name: ffc-demo-claim-service-db-migration-secret