apiVersion: batch/v1
kind: Job
metadata:
  name: ffc-demo-claim-service-db-migration
  namespace: ffc-demo
  labels:
    azure.workload.identity/use: "true"
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ffc-demo
      restartPolicy: Never
      containers:
      - name: ffc-demo-claim-service-db-migration
        image: sndadpinfcr1401p.azurecr.io/image/ffc-demo-claim-service-migration:dev
        # command:
        #   - sh
        #   - -c
        #   - "/scripts/migration/database-up"
        imagePullPolicy: Always
        env:
        - name: POSTGRES_HOST
          value: "${POSTGRES_SERVER}.postgres.database.azure.com"
        - name: SCHEMA_NAME
          value: "public"
        - name: POSTGRES_DB
          value: "ffc-demo-claim"
        - name: POSTGRES_PORT
          value: "5432"
        - name: SCHEMA_USERNAME
          value: "sndadpinfmid1401gg-workload-ffc-demo" #{TEAM_MI_PREFIX}-${SERVICE_NAME}
        # envFrom:
        # - secretRef:
        #     name: ffc-demo-claim-service-db-migration-secret