apiVersion: batch/v1
kind: Job
metadata:
  name: test-access-token
  namespace: ffc-demo
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ffc-demo
      restartPolicy: Never
      containers:
      - name: test-access-token
        image: sndadpinfcr1401p.azurecr.io/image/test-access-token:dev4
        imagePullPolicy: Always
        env:
        - name: CLIENT_ID
          value: ${WORKLOAD_IDENTITY_ID}
        - name: OBJECT_ID
          value: "3ad8c7f6-8291-4e2a-b115-b6c395da9266"
