apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - deploy-kustomize.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - image-repository.yaml  
  - image-policy.yaml

patches:
  - path: "../${ENVIRONMENT}-${CLUSTER}.yaml"