apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adp-platform-aso-credential
  namespace: flux-config
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: flux-config
  interval: 5m
  timeout: 3m
  prune: true
  path: ./services/adp-platform/aso-credential
  postBuild:
    substitute:
      TEAM_NAME: ${TEAM_NAME}
      TEAM_NAMESPACE: "flux-config"
      PLATFORM_DB_ADMIN: ${PLATFORM_DB_ADMIN}
    substituteFrom:
      - kind: ConfigMap
        name: adp-platform-mi-credential
        optional: true
      - kind: ConfigMap
        name: adp-platform-vars
