apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-cluster-flux
  namespace: config-cluster-flux
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: config-cluster-flux
  interval: 5m
  timeout: 3m
  prune: true
  path: ./services/environments/snd/01
  postBuild:
    substitute:
      ENVIRONMENT: "snd"
      ACR_NAME: "sndadpinfcr1401"
      CLUSTER: "01"
      CLUSTER_OIDC: "https://uksouth.oic.prod-aks.azure.com/6f504113-6b64-43f2-ade9-242e05780007/43949ff1-720e-44d1-b2a8-b0a35bf39dda/"
      TENANT_ID: "6f504113-6b64-43f2-ade9-242e05780007" 
      SUBSCRIPTION_ID: "55f3b8c6-6800-41c7-a40d-2adb5e4e1bd1"
      SUBSCRIPTION_NAME: "AZD-ADP-SND1"
      SERVICEBUS_RG: "SNDADPINFRG1401"
      SERVICEBUS_NS: "SNDADPINFSB1401"
      INFRA_RG: "SNDADPINFRG1401"
      TEAM_MI_NAME: "ffc-demo-temp"
      POSTGRES_SERVER_RG: "SNDADPDBSRG1401"
      POSTGRES_SERVER: "sndadpdbsps1401"

